name: JSON Placeholder API Testing with Positif and Negatif TestCase

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify
  test:
    name: TEST API AUTOMATION Positif Negatif Branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
      - name: Test API JSONPlaceholder
        run: mvn clean verify